# Generated by Django 5.0 on 2024-01-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_school_renteremail_school_semail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='semail',
            new_name='email',
        ),
    ]
